### ISSUE TITLE
[Bug]: Log entry for EP Token should be redacted

### ISSUE THREAD

**Issue by dennis-brinley** [SolaceLabs/ep-asyncapi-sap-is-converter#10]
### Bug Description

Log entry for `Validating user EP token input` should not include the text of the token. Token should be redacted.

`2024-08-20T11:08:48.627-04:00 DEBUG 32981 --- [ep-asyncapi-sap-is-converter] [nio-9003-exec-6] .t.s.i.c.c.EpAsyncAPIConverterController : Validating user EP token input:eyJhbGciOiJS...`

### Expected Behavior

Exclude/redact token text from log entry

### Steps to Reproduce

- Run the app
- validate an EP token
- view logs

**Comment by HariRangarajan-Solace** [comment]
https://github.com/SolaceLabs/ep-asyncapi-sap-is-converter/pull/12
